[project]
name = "primitive-db"
version = "0.1.0"
description = "Примитивная база данных: таблицы с типами, CRUD-операции и хранение в JSON"
readme = "README.md"
authors = [
    { name = "Maksim Lapin", email = "maksim@lapin.sh" }
]
requires-python = ">=3.12"
dependencies = [
    "prettytable>=3.18.0",
    "prompt>=0.4.1",
]

[project.scripts]
database = "primitive_db.main:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.10",
]

[tool.ruff]
line-length = 88
target-version = "py312"
exclude = ["venv", ".venv", "dist", "__pycache__"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []
